spring.application.name=registrar
server.port=8080
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.hibernate.ddl-auto=update
# set show-sql=true for debugging
spring.jpa.show-sql=true
rsa.privateKey = classpath:certs/private.pem
rsa.publicKey = classpath:certs/public.pem
spring.sql.init.continue-on-error=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect